import os

# path to save data
BASE_PATH=os.getcwd()

# money stuff
MONEY_INIT=100
MONEY_ASKED=2
MONEY_ASKED_INCR=0.3
MONEY_ASKED_DEC=0.3
VALUE_OF_EDUCATION=5

# role stuff
TIME_TO_FUCK_OFF=(0.9,3)#percent, past X years
TIME_TO_INCR=(0.8,1,MONEY_ASKED_INCR)#percent, past X years,increase percent
TIME_TO_DEC=(0.5,1,MONEY_ASKED_DEC)#percent, past X years,decrease percent
REJECT_ODD=0
REJECT_ODD_INCR=0.005
OFFICER_NUM=1
COMMON_NUM=30
BREAKER_NUM=1

#game limit
START_YEAR=1
MAX_YEAR=30




TABLE_STATUS={
    "BASE_PATH":BASE_PATH,
}


ADMIN_STATUS={
    "REJECT_ODD":REJECT_ODD,
    "REJECT_ODD_INCR":REJECT_ODD_INCR,
}

OFFICER_STATUS={
    "MONEY":MONEY_INIT,
    "MONEY_ASKED":MONEY_ASKED,
    "MONEY_ASKED_INCR":MONEY_ASKED_INCR,
    "MONEY_ASKED_DEC":MONEY_ASKED_DEC,
    "TIME_TO_FUCK_OFF":TIME_TO_FUCK_OFF,
    "TIME_TO_INCR":TIME_TO_INCR,
    "TIME_TO_DEC":TIME_TO_DEC,
}

COMMON_STATUS={
    "MONEY":MONEY_INIT,
    "VALUE_OF_EDUCATION":VALUE_OF_EDUCATION,
}



BREAKER_STATUS={
    "MONEY":MONEY_INIT,
    "VALUE_OF_EDUCATION":VALUE_OF_EDUCATION,
}



